# 빈도수 기반 텍스트 표현 (BoW, TF-IDF)

## BOW 기반의 카운트 벡터 생성

* 사이킷런의 CountVectorizer 클래스 활용 연습
    * sklearn 설치 : **pip install scikit-learn**

In [1]:
pip install scikit-learn

  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 8.1/8.1 MB 76.1 MB/s  0:00:00
Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   -------------------- ------------------- 19.4/37.3 MB 91.0 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 87.5 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 77.2 MB/s  0:00:00

   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ----------------

### 영어 문서 카운트 벡터 추출

In [2]:
sample_corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

In [3]:
# Vectorizer 객체 생성
from sklearn.feature_extraction.text import CountVectorizer

# 특징 집합 생성
cVectorizer = CountVectorizer()

# 카운트 벡터 생성
dtm = cVectorizer.fit_transform(sample_corpus)


# DTM 출력
print(dtm.toarray())


[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [4]:
# 참고
feature_set = cVectorizer.vocabulary_
print(feature_set)

# index 0부터 출력
print(sorted(feature_set.items(), key=lambda x : x[1]))

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
[('and', 0), ('document', 1), ('first', 2), ('is', 3), ('one', 4), ('second', 5), ('the', 6), ('third', 7), ('this', 8)]


### 한글 문서 카운트 벡터 추출

In [5]:
sample_corpus = [
    '자연어처리 강의를 시작하겠습니다.',
    '자연어처리는 재미있습니다.',
    '밥을 먹고 강의를 듣고 있습니다.',
    '이번 자연어처리 강의는 한국어 자연어처리입니다.' 
]

In [6]:
from konlpy.tag import Okt
def my_tokenizer(text):
    my_tags = ['Noun']
    my_stopwords = ['이번']
    return [ word for word, tag in Okt().pos(text) if tag in my_tags and word not in my_stopwords]

ModuleNotFoundError: No module named 'konlpy'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Vectorizer 객체 생성
vectorizer = CountVectorizer(tokenizer=my_tokenizer)

# 특징 집합 생성
vectorizer.fit(sample_corpus)
vectorizer.get_feature_names_out()

# 카운트 벡터 생성
dtm = vectorizer.transform(sample_corpus)
print(dtm.toarray())
# DTM 출력


## TF-IDF 벡터 생성
* sklearn.feature_extraction.text.TfidfVectorizer 사용
1. 한글 토크나이저 정의
2. 특징 추출 모델 생성 : Vectorizer -> fit()
3. 문서별 특징 벡터 추출 : transform()

### 한글 토크나이저 정의

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(tokenizer=my_tokenizer)
vectorizer.fit(sample_corpus)
print(vectorizer.get_feature_names_out())

dtm = vectorizer.transform(sample_corpus)
dtm.toarray()



### 특징 추출 모델 생성 : TfIdfVectorizer

In [ ]:
# TfIdfVectorizer 객체 생성 (tokenizer 지정, 최대 단어 수지 지정)
from sklearn.feature_extraction.text import TfidfVectorizer
from konlpy.tag import Okt
tVectorizer = TfidfVectorizer(tokenizer=my_tokenizer, max_features=1000)

### 문서별 특징 벡터 추출

In [ ]:
# 특징 집합과 특징 벡터 계산을 위한 데이터 추출
from sklearn.feature_extraction.text import TfidfVectorizer

tVectorizer = TfidfVectorizer(tokenizer=my_tokenizer, max_features=1000)


In [ ]:
# 특징 벡터 추출
tfidf_dtm = tVectorizer.fit_transform(sample_corpus)


## 다음(Daum) 영화 리뷰 TF-IDF 벡터 추출

In [ ]:
# csv 파일 → DataFrame으로 업로드

import pandas as pd
df = pd.read_csv('daum_movie_reviews.csv')

In [ ]:
# Vectorizer 객체 생성
tVectorizer = TfidfVectorizer(tokenizer=my_tokenizer, max_features=1000)

In [ ]:
# Vectorizer 모델 생성
tfidf_matrix = tVectorizer.fit_transform(df['review'])

In [ ]:
# 특징 집합 구성 단어 확인
print(tVectorizer.get_feature_names_out()[:20])

In [ ]:
# 새로운 텍스트의 tfidf 특징 벡터 추출
new_text = ["꿀잼"]
new_vector = tVectorizer.transform(new_text)
print(new_vector.toarray())

**[참고] Tfidf 특징 벡터 추출 모델을 파일로 저장하기**