# 1. 넘파이 (NumPy : Numerical Python)

In [2]:
import numpy as np

## 1-1. ndarray 데이터 확인
- ndarray.shape : ndarray의 (행의 수, 열의 수) 튜플
- ndarray.ndim : ndarray 차원
- ndarray.dtype : ndarray 내 데이터 타입
- ndarray.astype(*'data_type'*)
- python type(*data*) : data의 데이터 타입

## 1-2. 데이터 세트 선택 (Indexing) : [ ]
- 단일값 추출: [*index*]
- Slicing : [*start*:*stop*:*step*]
- Boolean Indexing : [*Boolean Condition*]
- Fancy Indexing : [*list of index*]
- index, start, end의 값이 음수인 경우 배열의 뒤에서부터 indexing


### Slicing : [*start*:*stop*:*step*]

In [16]:
# array1에 0부터 11까지의 1차원 배열 생성
array1 = np.arange(10)
print(array1)

# 앞에서 3개 요소 반환
print(array1[:3])
print(array1[0:3:1])
print(array1[:3:])

# 앞에서 3번째부터 마지막 요소까지 반환
print(array1[2:])
print(array1[2::2])

# 전체 반환
print(array1[:])

# 뒤에서 3번째 부터 반환
print(array1[-3:])

# 앞에서부터 뒤에서 3번째 요소까지 반환
print(array1[:-2])

# 뒤에서부터 모두 반환
print(array1[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[0 1 2]
[0 1 2]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[7 8 9]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]


### Boolean Indexing : [*Boolean Condition*]

In [20]:
array1d = np.arange(start=1, stop=10)
print(array1d)

# 5보다 큰 값만 출력
array2 = array1d[array1d > 5]
print(array2)

# 5보다 크고 8보다 작은 값만 출력
array3 = array1d[(array1d > 5) & (array1d <8)]
print(array3)


[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[6 7]


In [23]:
boolean_indexes = np.array([True, False, False, False, False,  True,  False,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [1 6 8 9]


### Fancy Indexing : [*list of index*]

In [27]:
print(array1d)
# index 5, 1, 3, 2 순서대로 데이터 출력
indexes = [5, 1, 0, 2]
array4 = array1d[indexes]
print(array4)

[1 2 3 4 5 6 7 8 9]
[6 2 1 3]


## 1-3. 정렬 : sort( )와 argsort( )

- numpy.sort(*ndarray*, axis=) : 원 행렬 변경없음 → 반환값 활용
- ndarray.sort() : 원 행렬 변경 → 반환값 없음
- numpy.argsort(*ndarray*) : 정렬 시의 index 순서 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])

# np.sort( )로 정렬 후 원 행렬과 반환값 출력

# ndarray.sort( )로 정렬 후 원 행렬과 반환값 출력

# no.argsort()로 인덱스만 반환


In [ ]:
# 내림차순으로 정렬

# 행렬 내림차순 정렬 시 원본 행렬의 인덱스 출력


#### [연습문제] 이름과 성적이 각각의 ndarray로 주어진 경우 이름을 성적 순서로 출력하기

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])



# 2. 판다스 (Pandas)
#### DataFrame 기반 데이터 핸들링

In [ ]:
import pandas as pd

## 2-1. 파일을 DataFrame으로 로딩
- pandas.read_csv(*file_path/url*, sep=, encoding=, ...)
- pandas.read_json(*file_path/url*, encoding=, ...)

In [ ]:
# sample_data.csv 로딩


## 2-2. 데이터 확인을 위한 속성 및 메서드
- dataframe.head(*num_row=5*) : 앞 부분 출력
- dataframe.tail(*num_row=5*) : 뒷 부분 출력
- dataframe.shape : 행, 렬의 크기
- dataframe.info() : 데이터 갯수, null값(결측치, NaN) 등 확인
- python len(*dataframe*) : 데이터 갯수
- dataframe.describe() : 기술 통계값
  - 데이터형이 float나 int인 열에만 적용
  - 각 열의 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 최댓값(max) 등의 통계치 확인 가능
- dataframe.value_counts(dropna=True) : 속성값별 갯수

In [ ]:
# 앞부분 3열


In [ ]:
# 크기, 갯수, 결측치 확인


In [ ]:
# 기술 통계 확인


In [ ]:
# 특정 컬럼의 값 범위와 갯수 확인
# 'City' 값 범위와 갯수

# null값까지 포함하여 확인


## 2-3. DataFrame 생성 : pd.DataFrame()
    * pd.DataFrame(*list/ndarray*, columns=)
    * pd.DataFrame(*dictionary*)
        * Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)

## 2-4. 결측치 처리하기
* 결측치 확인 : info(), isnull()
* 결측치 포함 행 삭제 : dataframe.dropna(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)
* 새로운 값으로 채우기 : dataframe.fillna(value, inplace=)
   * 특정 컬럼에 해당하는 값만 채우려는 경우 : DataFrame **[** *name* **]**.**fillna**(...)

In [ ]:
# sample_data.csv을 dataframe으로 로딩하여 결측치 확인


In [ ]:
# 결측치 확인 : 컬럼별 결측치 갯수 계산

In [ ]:
# 결측치가 있는 행 추출 


In [ ]:
# 결측치가 있는 행 삭제


## 2-5. 중복값 처리하기
* 중복값 확인 : duplicated(keep=)
    - keep = True (첫번째 미포함)
* 중복값 삭제 : drop_duplicates(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)

In [ ]:
# index 조정


In [ ]:
# 중복값인 행 확인


In [ ]:
# 중복값인 행 추출


In [ ]:
# 중복값인 행 삭제


## 2-6. 컬럼 생성, 수정, 삭제
* dataframe['컬럼명'] = data
* dataframe['컬럼명'] = dataframe 컬럼 간 연산
* drop(*컬럼명 리스트*, axis=1, inplace=)

In [ ]:
# 'Age' 칼럼의 값에 모두 10을 곱한 'Age_by_10' 칼럼 생성


In [ ]:
# 'Age_0' 컬럼 삭제


## 2-7. 정렬

* dataframe.sort_values(by=컬럼리스트, ascending=True/False)

In [ ]:
# 'City' 정보를 기준으로 정렬


## 2-8. 데이터 선택

### [ ] 연산자
    - 칼럼명 : 컬럼 선택
    - Slicing : 행 slicing만 가능
    - Boolean Indexing : 행 데이터 추출만 가능
    - 행 번호 지정 불가
### loc[*행 index*,  *칼럼명*] 연산자
    - 명칭(label) 기반 indexing
        - indexing에 label 사용
        - 행 index에 label이 없는 경우 숫자를 label로 사용
    - Slicing, Boolean Indexing
    - Slicing에 컬럼명을 사용해야함
### iloc[*행 indexing 값*, *열 indexing 값*] 연산자
    - 위치(integer location) 기반 indexing
    - Slicing, Boolean Indexing

In [ ]:
# 'Name' 칼럼 출력


In [ ]:
# 'Name', 'Gender' 칼럼 출력


In [ ]:
sample_df['Name':'Gender']

In [ ]:
# 1행부터 3행까지 출럭


In [ ]:
# Bob에 대한 정보 출력


In [ ]:
# Bob의 나이 확인


In [ ]:
# Alice와 Susan의 이름, 나이, 성병 확인


In [ ]:
# 나이가 25세 넘는 사람


In [ ]:
# 나이가 25세 넘는 사람들의 이름, 나이, 도시
